from tkinter import Canvas, ttk


def build_lut_tab(app, parent):
    parent = app._scrollable_frame(parent)
    parent.columnconfigure(0, weight=1)
    setup = ttk.LabelFrame(parent, text="LUT 批量缩略图对比", padding=12)
    setup.grid(row=0, column=0, sticky="ew")
    setup.columnconfigure(1, weight=1)
    ttk.Label(setup, text="视频文件").grid(row=0, column=0, sticky="w", pady=5)
    ttk.Entry(setup, textvariable=app.lut_page_video).grid(row=0, column=1, sticky="ew", padx=8)
    ttk.Button(setup, text="选择…", command=app.choose_lut_page_video).grid(row=0, column=2)
    ttk.Label(setup, text="LUT 文件夹").grid(row=1, column=0, sticky="w", pady=5)
    ttk.Entry(setup, textvariable=app.lut_page_folder).grid(row=1, column=1, sticky="ew", padx=8)
    ttk.Button(setup, text="选择…", command=app.choose_lut_page_folder).grid(row=1, column=2)
    ttk.Button(setup, text="输出目录", style="OutputDir.TButton", command=lambda: app.open_output_dir(app.lut_page_output)).grid(row=2, column=0, sticky="w", pady=5)
    ttk.Entry(setup, textvariable=app.lut_page_output).grid(row=2, column=1, sticky="ew", padx=8)
    ttk.Button(setup, text="选择…", command=app.choose_lut_page_output).grid(row=2, column=2)
    ttk.Label(setup, text="取帧时间").grid(row=3, column=0, sticky="w", pady=5)
    ttk.Spinbox(setup, from_=0, to=3600, increment=0.5, textvariable=app.lut_page_time).grid(row=3, column=1, sticky="ew", padx=8)
    ttk.Button(setup, text="▶ 生成所有 LUT 缩略图", style="Accent.TButton", command=app.start_lut_folder_preview).grid(row=4, column=0, columnspan=3, sticky="ew", pady=(12, 0))

    result = ttk.LabelFrame(parent, text="缩略图结果", padding=12)
    result.grid(row=1, column=0, sticky="nsew", pady=(10, 0))
    result.columnconfigure(0, weight=1)
    result.rowconfigure(0, weight=1)
    app.lut_result_canvas = Canvas(result, height=240, bg=app.COLORS["surface_alt"], highlightthickness=1, highlightbackground=app.COLORS["panel_border"])
    app.lut_result_canvas.grid(row=0, column=0, sticky="nsew")
    lut_scroll = ttk.Scrollbar(result, orient="horizontal", command=app.lut_result_canvas.xview)
    lut_scroll.grid(row=1, column=0, sticky="ew", pady=(8, 0))
    app.lut_result_canvas.configure(xscrollcommand=lut_scroll.set)
    app.lut_result_strip = ttk.Frame(app.lut_result_canvas)
    app.lut_result_window = app.lut_result_canvas.create_window((0, 0), window=app.lut_result_strip, anchor="nw")
    app.lut_result_strip.bind("<Configure>", lambda event: app.lut_result_canvas.configure(scrollregion=app.lut_result_canvas.bbox("all")))
